---

- name: Download ckan deb
  get_url:
    url: http://packaging.ckan.org/python-ckan_2.5-trusty_amd64.deb
    dest: /tmp/python-ckan_2.5-trusty_amd64.deb

- name: Setup dirs
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ CKAN_HOME }}"
    - "{{ CKAN_CONFIG }}"
    - "{{ DEFAULT_CKAN_DATA }}"
    - "{{ CKAN_INIT }}"
    - "{{ CKAN_DIST_CONFIG }}"
    - "{{ UPDATE_DIR }}"

- name: Setup ckan_init.d subdirectories
  file:
    dest: "{{ CKAN_INIT }}/{{ item }}"
    state: directory
  with_items:
    - tests
    - run
    - config

- name: Create virtualenv
  pip:
    name: pip
    virtualenv: "{{ CKAN_HOME }}"

- name: Create who.ini link
  file:
    state: link
    force: yes
    src: "{{ CKAN_HOME }}/src/ckan/who.ini"
    dest: "{{ CKAN_CONFIG }}/who.ini"


- name: Install ckan
  apt:
    deb: /tmp/python-ckan_2.5-trusty_amd64.deb

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ CKAN_HOME }}"

- name: Install python requets
  pip:
    name: requests[security]
    virtualenv: "{{ CKAN_HOME }}"

- name: Install custom packages
  pip:
    name: "{{ item }}"
    virtualenv: "{{ CKAN_HOME }}"
  with_items:
    - git+https://github.com/datagovuk/ckanext-hierarchy.git@3f2a258a46d5577c449678bf83f0ec1c6b6e7795#egg=ckanext-hierarchy
    - git+https://github.com/ckan/ckanext-googleanalytics.git@v2.0.2#egg=ckanext-googleanalytics

- name: Install some requirements
  pip:
    name: "{{ item }}"
    virtualenv: "{{ CKAN_HOME }}"
  with_items:
    - pyyaml
    - lepl
    - jsonschema
    - rfc3987

- name: Install datajson AR
  pip:
    name: git+https://github.com/datosgobar/ckanext-datajsonAR.git@v0.1.1#egg=ckanext-datajson
    virtualenv: "{{ CKAN_HOME }}"

- name: Change owners
  file:
    owner: www-data
    group: www-data
    path: "{{ item }}"
  with_items:
    - "{{ CKAN_DIST_CONFIG }}"
    - "{{ DEFAULT_CKAN_DATA }}"

- name: Change chmode
  file:
    mode: u+rwx
    path: "{{ item }}"
    recurse: yes
  with_items:
    - "{{ CKAN_DIST_CONFIG }}"
    - "{{ DEFAULT_CKAN_DATA }}"
